### ISSUE TITLE
Unable to extract Japanese characters

### ISSUE THREAD

**Issue by chezou** [tabulapdf/tabula-java#114] opened 2016-10-24 03:54 UTC
I tried to extract [Japanese PDF](http://www.jma.go.jp/jma/kishou/know/amedas/ame_master.pdf), tabula-java failed to extract Japanese characters.

Are there any option or settings required?

```
$ java -jar ./tabula-0.9.1-jar-with-dependencies.jar -p 6 ame_master.pdf                                                       
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
"??? ??? ?? ???",??,????,,????,???,,?? ? ?,?? ?,? ??(?)??(?)??(?),???? ???? ????,,???????,??1,??2
"?????????",,,,,,,,,,,,,,
"??",12011? ??,,,???? ????????,,,44497.142 4.6,,,,22 10 1.5?52.190.1,,? ?,
"??",12014? ????,,,?????? ????????????,,,44436.142159.,,,,40 10 1.5?52.170.1,,1295?0,
"??",12066? ??,,,???? ?????????,,,44365.142177.,,,,62? ? ?17.191.,,? ?,
"??",1214? ??,,,???? ????????,,,44288.142205.,,,,77 10 1.5#?52.160.,,1290?0,
"??",1218? ??,,,?? ?????,,,44222.142274.,,,,89 8 2.6#?51.14.,,1290?1,
"??",12271? ???,,,?????? ?????????,,,44177.142215.,,,,128? ? ?17.181.,,? ?,
"??",12213? ??,,,???? ????????,,,44181.142374.,,,,140 10 2.4#?52.140.1,,1295?2,
"??",12265? ??,,,???? ????????,,,44 6.4142212.,,,,138? ? ?17.101.1,,? ?,
"??",12216? ??,,,???? ??????,,,44112.142250.,,,,135 8 1.5#?52.130.1,,? ?,
"??",12266? ??,,,?? ????????,,,44 7.1142357.,,,,225 10 1.5?52.130.1,,? ?,
"??",12310? ??,,,???? ??????????,,,44 1.7142246.,,,,150 10 1.5?52.120.1,,1295?1,
"??",12368? ???,,,?????? ?????????,,,43522.142156.,,,,140 10 3.2?52.110.1,,? ?,
"??",12369? ??,,,???? ????????,,,43525.142288.,,,,175 10 2.5(?50.5.?2572).110.1?,,?,
"??",12411? ??,,,???? ????????,,,43508.142452.,,,,324 10 2.4#?52.120.1,,1290?2,
"??",12424? ??,,,???? ?????1?????????,,,43454.142223.,,,,120 464.? ?16.99.,,1297?2,
"??",12415? ??,,,?????? ????????,,,43421.142305.,,,,215 10 2.2?52.150.,,? ?,
"??",12475? ??,,,???? ?????????,,,43442.142383.,,,,289? ? ?59.180.,,? ?,
"??",12417? ???,,,?????? ???????????,,,43452.142558.,,,,540? ? ?50.57.2,,1290?3,
"??",12510? ???,,,???????? ????????2???????????,,,43402.142268.,,,,21 9.4? ?15.11.,,1292?3????,
"??",12521? ???,,,???? ??????????,,,43386.142349.,,,,310 10 1.5?4.190.,,? ?,
"??",12515? ??,,,???? ????????5?,,,43353.142296.,,,,250 10 1.5(?50.5.?2582).160. 1295?3,,,
"??",12569? ????,,,???? ??????????,,,43273.142279.,,,,220 10 2.1?52.180.,,? ?,
"??",12670? ??,,,???? ????????,,,43285.142390.,,,,658? ? ?59.180.,,? ?,
"??",1262? ???,,,?? ??????,,,43200.142240.,,,,174 9.4 2.2#?51.14.,,1290?4,
"??",12623? ??,,,???? ?????????,,,43181.142313.,,,,315 10 2.3?53.150.2,,? ?,
"??",1268? ??,,,???? ????????????,,,43 8.3142250.,,,,284? ? ?17.171.1,,? ?,
"??",12619? ??,,,???? ??????????,,,43101.142341.,,,,350 9.4 1.5?52.170.,,1295?4,
"??",12764? ??,,,?????? ???????????,,,42587.142237.,,,,332 10 1.5?52.170.,,1290?5,
"??",15014? ???,,,?????? ??????????,,,44169.142 9.7,,,,25 10 1.5?53.140.2,,1590?0,
"??",15067? ???,,,???? ??????????,,,44 0.6142 9.6,,,,159 9.4 1.5(?50.5.?2582).180.21595?0,,,
"??",13016? ??,,,?? ????????,,,44536.141457.,,,,9 10 1.5#?52.160.2,,1390?0,
"??",13068? ??,,,???? ????????,,,44431.141484.,,,,7 10 1.5#?52.160.2,,? ?,
"??",1312? ???,,,?????? ??????????,,,44314.141462.,,,,27 10 1.5?52.180.2,,1395?0,
"??",13164? ??,,,???? ??????????,,,44257.141253.,,,,38 8 1.5?52.170.2,,? ?,
"??",1318? ??,,,???? ???????3?????????????,,,44218.141420.,,,,8 214.? #?51.11.,,1397?0,
"??",13260? ???,,,?????? ?????????,,,44159.141433.,,,,15? ? ?51.48.,,1390?1,
"??",13216? ??,,,???? ????????,,,44 2.9141514.,,,,30 10 3.4?52.110.3,,? ?,
"??",13277? ??,,,?? ?????????????????,,,43567.141379.,,,,24 163.? ?55.61.2,,1395?1,
"??",13311? ??,,,?? ????????,,,43509.141306.,,,,20 9.4 1.5#?53.140.2,,? ?,
"??",13312? ??,,,???? ??????,,,43512.141456.,,,,20 10 1.5?52.110.3,,1390?2,
```

**Comment by criztovyl** [comment] 2016-10-25 22:18
Can reproduce.

**Comment by chezmo** [comment] 2016-10-26 14:50
same here, getting ? for special characters. Any way to have UTF8 characters working?

**Comment by jeremybmerrill** [comment] 2016-10-26 15:45
@chezmo what language are you working with? also japanese?

**Comment by chezmo** [comment] 2016-10-26 16:33
Czech in my case

**Comment by jeremybmerrill** [comment] 2016-10-26 16:53
I can replicate this with @chezou's PDF. that's certainly an odd result, because the tool's test set does support Arabic, Hebrew and Hindi (along with a bunch of languages written in roman characters, including Spanish with diacritics). 

@chezmo Are you able to give me your PDF? I'd like to have two to test against. I"ll caution you both that I likely won't be able to look into this until after the US election...

**Comment by chezmo** [comment] 2016-10-27 11:32
hey @jeremybmerrill ! Please ignore my comments. I just tested on a different machine and it works great. So I guess I need to check the charset settings of my server.

**Comment by chezmo** [comment] 2016-10-27 11:46
@jeremybmerrill quick update, I just forgot to append `-Dfile.encoding=utf-8` to the java command.

**Comment by jeremybmerrill** [comment] 2016-10-27 15:20
@chezmo Okay, great, glad it works. @chezou I will continue researching why Tabula is mis-handling your Japanese text.

**Comment by jeremybmerrill** [comment] 2016-10-27 15:33
@chezou: I figured it out. Unfortunately, this is a bug with PDFBox -- the underlying library which Tabula uses to parse PDFs -- where the latest 1.x version of PDFBox fails to handle this PDF's Japanese characters correctly. 

This bug will be fixed automatically when Tabula is upgraded to PDFBox 2.0. Manuel is working on it at https://github.com/tabulapdf/tabula-java/issues/52.

I'm closing the bug because there's nothing we can do to solve this in particular other than #52.

**Closed by jeremybmerrill** 2016-10-27 15:33 UTC

**Comment by jazzido** [comment] 2016-10-27 19:28
Confirming @jeremybmerrill 's report.

With PDFBox 1.8.12:

![screen shot 2016-10-27 at 3 26 41 pm](https://cloud.githubusercontent.com/assets/27584/19781981/d734d9c8-9c59-11e6-9be4-9cbd304d8238.png)

With PDFBox 2.0.3:

![screen shot 2016-10-27 at 3 27 47 pm](https://cloud.githubusercontent.com/assets/27584/19782012/f360ab86-9c59-11e6-8c1d-0ff274628c80.png)

**Comment by chezou** [comment] 2016-10-27 22:58
Thanks! I'm looking forward to bumping up 😄

**Comment by narendragillalu** [comment] 2020-11-25 06:55
I am working with for extracting tabular data from pdfs but there is special character as in shown image. But after extracting text from pdf .I am getting as Ã"89-140mm).Can someone help. Thanks in advance


![thumbnail_image001](https://user-images.githubusercontent.com/54871087/100191589-6712bf80-2f16-11eb-8967-0702ec32991e.jpg)
