### ISSUE TITLE
cli: -l and -t parameters have no effect

### ISSUE THREAD

**Issue by fleger** [tabulapdf/tabula-java#141] opened 2017-02-14 17:03 UTC
Hi,

Using tabula 0.9.2, the -l and -t parameters are not working as expected.
Deprecated parameters -r and -n are working fine.

**Comment by criztovyl** [comment] 2017-02-14 18:10
[CommandLineApp#whichExtractionMethod](https://github.com/tabulapdf/tabula-java/blob/master/src/main/java/technology/tabula/CommandLineApp.java#L226) seems to use `-r` and `-n`.

**Comment by criztovyl** [comment] 2017-02-14 22:14
Fixed with #142.

**Comment by fleger** [comment] 2017-02-15 10:49
Thanks.

**Comment by criztovyl** [comment] 2017-02-16 21:02
@fleger You may close this issue, if the problem is fixed. :)

**Closed** 2017-02-17 09:33 UTC
