### ISSUE TITLE
BasicExtractionAlgorithm - extract methods deletes first character for each execution of same page

### ISSUE THREAD

**Issue by DouglasROPB** [tabulapdf/tabula-java#78] opened 2016-05-04 02:04 UTC
Problem example:
If I use extract in pdf page beginning by 'Access':
Result:
Access
If I use again
Result:
ccess

It occurs in TextElement.mergeWords:

121: textChunks.add(new TextChunk(textElements.remove(0)));

Workaround:
public static Table safeExtract(final ExtractionAlgorithm extractor, final Page page) {
    final List<TextElement> textsBackup = UtilitiesParser.backupPageTexts(page);
    final List<? extends Table> tableList = extractor.extract(page);
    final Table table = UtilitiesCollections.getFirst(tableList);
    UtilitiesParser.renewTexts(page, textsBackup);
    return table;
}
public static void renewTexts(final Page page, final List<TextElement> textsBackup) {
    final List<TextElement> texts = page.getTexts();
    texts.clear();
    texts.addAll(textsBackup);
}

**Comment by jeremybmerrill** [comment] 2016-05-05 14:45
Oddly, I'm seeing the same thing.

**Comment by jeremybmerrill** [comment] 2016-11-20 04:14
@DouglasROPB: Unlikely, I know, since I've let this languish for a long time, but do you still have a test case handy that you could share? (I believe that you're probably right about the cause of the problem -- and I was able to repro it 6 months ago -- and I coded up a fix in the bugfix/78 branch, but I want to create a test case to make sure.)

**Comment by jeremybmerrill** [comment] 2016-11-21 16:28
````
pdf_filename = "your_pdf.pdf"
require 'tabula'

extractor = Tabula::Extraction::ObjectExtractor.new(pdf_filename)
pages = extractor.extract.to_a 
first_page = pages.first
text_chunks = Tabula::TextElement.merge_words(first_page.texts)
first_text_chunk = text_chunks.first.text
text_chunks_again = Tabula::TextElement.merge_words(first_page.texts)
first_text_chunk_again = text_chunks_again.first.text

raise StandardError, "first text chunk loses a letter each time merge_words is called" if first_text_chunk[1..-1] == first_text_chunk_again
raise StandardError, "something else is going wrong" unless first_text_chunk == first_text_chunk_again
````

Here's a minimal test case. I'm going to test my branch against it.

**Comment by jeremybmerrill** [comment] 2016-11-21 20:03
closed in https://github.com/tabulapdf/tabula-java/pull/122

**Closed by jeremybmerrill** 2016-11-21 20:03 UTC
Labels: bug
