### ISSUE TITLE
Upgrade pdfbox dependecy to version 2.1.0?

### ISSUE THREAD

**Issue by chzhong** [tabulapdf/tabula-java#136] opened 2017-02-06 07:43 UTC
PDFBox had upgraded to 2.1.0. When would tabula migrate to support new version of pdfbox?

**Comment by jeremybmerrill** [comment] 2017-02-06 13:36
Soon. Check out the https://github.com/tabulapdf/tabula-java/tree/pdfbox2.0 branch. @jazzido and @melisabok will be able to say whether the target is 2.0 or 2.1.

**Comment by melisabok** [comment] 2017-02-06 16:58
Yes, we are working on the migration to the version 2.0.4 that I see is the latest one, there is no version 2.1 yet.

**Comment by jazzido** [comment] 2017-02-06 17:02
Closing as duplicate of #52.

**Closed by jazzido** 2017-02-06 17:02 UTC
